apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "uCcsbcXXwJZ/Jlpgd5yaB27jBxKxGilA08/nWCD352kFTmfVodBYmsgArUgkL3r3\n2Fi1njHQqlNmkwYKwRvWjxzvf9NK7HjXqHYcIyt0zoacRYT58OZbXa+5e7dv7PoE\nSFviThjS8owBtlWCMSvHCOMyZAEDtkiJJH54AjNMdNM="
